shell magic to find python3

diff --git a/git-pr b/git-pr
--- a/git-pr
+++ b/git-pr
@@ -1,4 +1,34 @@
-#!/usr/bin/env python
+#!/bin/bash
+
+# From https://stackoverflow.com/questions/47882916/how-to-make-the-shebang-be-able-to-choose-the-correct-python-interpreter-between
+
+# Shell commands follow
+# Next line is bilingual: it starts a comment in Python, and is a no-op in shell
+""":"
+
+# Find a suitable python interpreter
+
+for cmd in python3 python /usr/local/Cellar/python/3.6.1/bin/python3 ; do
+    command -V >/dev/null $cmd 2>&1 && ( $cmd -V 2>&1 | grep -c 3 >/dev/null ) && exec $cmd $0 "$@"
+done
+
+for dir in /usr/local/Cellar/python/; do 
+    if [ -d "$dir" ]; then
+        pydir="$(ls -r1 $dir | grep '^3' | head -n 1)"
+        if [ -x "$dir/bin/python3" ]; then
+            exec "$dir/bin/python3" $0 "$@"
+        fi
+    fi
+done
+
+echo "Couldn't find a Python 3 interpreter!" >&2
+
+exit -2
+
+":"""
+# Previous line is bilingual: it ends a comment in Python, and is a no-op in shell
+# Shell commands end here
+# Python script follows (example commands shown)
 
 import sys
 from subprocess import *
